print("Addition functionality")
# print("Substraction functionality")
# print("Mul functionality")
print("Random functionality")
print("added some line in hotFix branch")
print("Substraction functionality")
print("Mul functionality")
#Adding a new comment while in Development branch
print("added some line in hotFix branch")
print("Hello World")
print("added some line in hotFix branch")
